import React from 'react';

function terms(props) {
    return (
        <div className="container">
            <h1 className="text-center">Terms and conditions</h1>
            <p> 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem deserunt, enim, voluptate similique neque aut aliquid asperiores harum sit distinctio unde odit laboriosam alias iure, vitae et. Mollitia, repellat nam? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque, esse. Temporibus consequuntur ducimus nisi consectetur. Dolorum quo ratione velit sapiente voluptas, doloremque iusto harum corrupti, sequi, vero quis consectetur voluptatem! 
            </p>
        </div>
    );
}

export default terms;